name: CI Build
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install --frozen-lockfile # optional, --immutable
      - name: Build
        run: |
          yarn build
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build.zip
          path: ./out
