name: CI/CD
on:
  push:
    branches:
      - develop
      - 'release/*'
      - master
jobs:
  select-env:
    name: Select Environment
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    outputs:
      environment_name: ${{ steps.select_env.outputs.environment_name }}
    steps:
      - name: Determine Environment
        id: select_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "environment_name=Production" >> $GITHUB_OUTPUT;
          elif [[ "${{ github.ref }}" =~ "refs/heads/release/" ]]; then
            echo "environment_name=Staging" >> $GITHUB_OUTPUT;
          else
            echo "environment_name=Development" >> $GITHUB_OUTPUT;
          fi
  infrastructure:
    name: Deploy Infrastructure
    uses: ./.github/workflows/cd-infrastructure.yml
    secrets: inherit
    needs: select-env
    concurrency:
      group: ${{ github.workflow }}-${{ needs.select-env.outputs.environment_name || inputs.environment }}
    with:
      environment: ${{ needs.select-env.outputs.environment_name || inputs.environment }}
  build:
    name: Build 🔧
    needs: infrastructure
    uses: ./.github/workflows/ci-build.yml
    with:
      asset-prefix: "https://${{ needs.infrastructure.outputs.cloudfront-distribution-domain-name }}/"
      static-asset-prefix: "https://${{ needs.infrastructure.outputs.cloudfront-distribution-domain-name }}"
      base-url: ''
  deploy:
    name: Deploy 🚀
    needs:
      - select-env
      - infrastructure
      - build
    uses: ./.github/workflows/cd-cloudfront.yml
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ needs.select-env.outputs.environment_name || inputs.environment }}
    with:
      environment: ${{ needs.select-env.outputs.environment_name || inputs.environment }}
      s3-bucket-prefix: ${{ vars.S3_BUCKET_PREFIX || '' }}
      s3-bucket-name: ${{ needs.infrastructure.outputs.s3-bucket-id }}
      cloudfront-distribution-id: ${{ needs.infrastructure.outputs.cloudfront-distribution-id }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}
