name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'release/*'
      - master
jobs:
  select-env:
    name: Select Environment
    runs-on: ubuntu-latest
    outputs:
      deploy_environment: ${{ steps.select_env.outputs.deploy_environment }}
      environment_name: ${{ steps.select_env.outputs.environment_name }}
    steps:
      - name: Determine Environment
        id: select_env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "environment_name=Production" >> $GITHUB_OUTPUT;
            echo "deploy_environment=PROD" >> $GITHUB_OUTPUT;
          elif [[ "${{ github.ref }}" =~ "refs/heads/release/" ]]; then
            echo "environment_name=Staging" >> $GITHUB_OUTPUT;
            echo "deploy_environment=stage" >> $GITHUB_OUTPUT;
          else
            echo "environment_name=Development" >> $GITHUB_OUTPUT;
            echo "deploy_environment=dev" >> $GITHUB_OUTPUT;
          fi
  infrastructure:
    name: Deploy Infrastructure
    uses: ./.github/workflows/cd-infrastructure.yml
    needs: select-env
    concurrency:
      group: ${{ github.workflow }}-${{ needs.select-env.outputs.deploy_environment }}
      cancel-in-progress: true
    with:
      environment: ${{ needs.select-env.outputs.environment_name }}
    secrets:
      aws-iam-assume-role-arn: ${{ secrets.AWS_IAM_ASSUME_ROLE_ARN }}
  build:
    name: Build 🔧
    needs: infrastructure
    uses: ./.github/workflows/ci-build.yml
    with:
      asset-prefix: ${{ needs.infrastructure.outputs.cloudfront_distribution_domain_name }}
      base-url: ''
  deploy:
    name: Deploy 🚀
    needs:
      - select-env
      - infrastructure
      - build
    uses: ./.github/workflows/cd-cloudfront.yml
    concurrency:
      group: ${{ github.workflow }}-${{ needs.select-env.outputs.deploy_environment }}
      cancel-in-progress: true
    with:
      environment: ${{ needs.select-env.outputs.deploy_environment }}
      s3-bucket-prefix: ''
      s3-bucket-name: ${{ needs.infrastructure.outputs.s3_bucket_id }}
      cloudfront-distribution-id: ${{ needs.infrastructure.outputs.cloudfront_distribution_id }}
      aws-region: ${{ needs.infrastructure.outputs.aws_region }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}
    secrets:
      aws-iam-assume-role-arn: ${{ secrets.AWS_IAM_ASSUME_ROLE_ARN }}
