# This is a basic workflow to help you get started with Actions
name: Github Pages CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build 🔧
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    uses: ./.github/workflows/ci-build.yml
    with:
      asset-prefix: ''
      base-url: ''
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
          lfs: true
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ./out
      - name: Display structure of downloaded artifacts
        run: ls -R
        working-directory: ./out
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./out # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.
