# This is a basic workflow to help you get started with Actions
name: Github Pages Build & Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - develop
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build 🔧
    needs: configure
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    uses: ./.github/workflows/ci-build.yml
    with:
      asset-prefix: ${{ needs.build.outputs.cloudfront_distribution_domain_name }}
      base-url: ''
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    needs:
      - build
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: ./out
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: out # The folder the action should deploy.
