name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'Development'
        options:
          - 'Development'
          - 'Staging'
          - 'Production'
jobs:
  infrastructure:
    name: Deploy Infrastructure
    uses: ./.github/workflows/cd-infrastructure.yml
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
    with:
      environment: ${{ inputs.environment }}
  build:
    name: Build 🔧
    needs: infrastructure
    uses: ./.github/workflows/ci-build.yml
    with:
      asset-prefix: ${{ needs.infrastructure.outputs.cloudfront-distribution-domain-name }}
      base-url: ''
  deploy:
    name: Deploy 🚀
    needs:
      - infrastructure
      - build
    uses: ./.github/workflows/cd-cloudfront.yml
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.environment }}
    with:
      environment: ${{ inputs.environment }}
      s3-bucket-prefix: ${{ vars.S3_BUCKET_PREFIX || '' }}
      s3-bucket-name: ${{ needs.infrastructure.outputs.s3-bucket-id }}
      cloudfront-distribution-id: ${{ needs.infrastructure.outputs.cloudfront-distribution-id }}
      artifact-name: ${{ needs.build.outputs.artifact-name }}
