on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-iam-assume-role-arn:
        required: true
jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Setup Runway
        uses: supplypike/setup-bin@v1
        with:
          uri: "https://oni.ca/runway/2.6.3/linux"
          name: 'runway'
          version: '2.6.3' # this enables caching
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws-iam-assume-role-arn }}
          role-session-name: github-actions
          aws-region: ${{ inputs.aws-region
      - name: Runway Deploy
        env:
          AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
          DEPLOY_ENVIRONMENT: ${{ inputs.environment }}
        run: runway deploy --ci
